CREATE DATABASE HOSPITAL_ANALYTICS_PROYECT_STUDENTS;
--Creacion de schemas
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS harmonized;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS automation;



